# Generated by Django 5.2.4 on 2025-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenceTracker', '0003_transactions_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='title',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.TextField(default='No description', max_length=150),
        ),
    ]
