# Generated by Django 5.2.3 on 2025-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenceTracker', '0004_rename_title_transactions_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='title',
            field=models.CharField(default='untitle', max_length=150),
        ),
    ]
