# Generated by Django 5.2.3 on 2025-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenceTracker', '0005_transactions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10),
        ),
    ]
